### ISSUE TITLE
In YAML, a module's inputs should be allowed to be empty if distribution_level is local

### ISSUE THREAD

**Issue by equant** [phytooracle/automation#104]
This fails.  I think it should not fail.  I'm working on this in 97-environment_association

```yaml
    distribution_level: local
    file_level:
    input_dir: [env_output]
    input_file: ignored
    inputs: []
    outputs: []
```
