### ISSUE TITLE
Pipeline needs ability to fetch/untar all contents from a cyverse directory

### ISSUE THREAD

**Issue by equant** [phytooracle/automation#38]
`3d_level_2_postprocessing.yaml` picks up from where `3d_level_1_preprocessing.yaml` left off (after landmark selection has been done) and needs to be able to fetch many tarballs from the alignment dir (and the newly added `transfromation.json`).

Here is what the dir contains...

```
/iplant/home/shared/phytooracle/season_11_sorghum_yr_2020/level_1/scanner3DTop/2020-08-12/alignment:
  2020-08-12_east.tar
  2020-08-12_east_downsampled.tar
  2020-08-12_merged.tar
  2020-08-12_merged_downsampled.tar
  2020-08-12_metadata.tar
  2020-08-12_west.tar
  2020-08-12_west_downsampled.tar
  transfromation.json
```

So we will add some yaml to direct `distributed_pipeline_wrapper.py` to DL all the files in the directory, and untar all of the tarballs...

```
  cyverse: 
    basename: /iplant/home/shared/phytooracle/
    input: 
      level: level_1
      input_dir: [alignment]
```

The old YAML where a single file is specified (i.e. with `prefix` and `suffix` will still work.
