### ISSUE TITLE
Necessary files DL location should be specified within `cyverse:input` not `module:input`

### ISSUE THREAD

**Issue by equant** [phytooracle/automation#39]
The module `inputs` is used by the workers as the path to the local input file.  This means we can't use this also as the location of the file on cyverse.  DLing logic should be triggered by the `cyverse` section of the YAML file, not the `module section`

We will add to `cyverse` `necessary_files`:

```
  cyverse:
    basename: /iplant/home/shared/phytooracle/

    input:
      necessary_files: [level_0/necessary_files/gcp_season_11.txt]
      level: level_0
      prefix: scanner3DTop-
      suffix: __*.tar.gz
    output:
      level: level_1
```

Also, all necessary_files will be downloaded into a local necessary files dir to keep the root automation directory a little cleaner.
